# Generated by Django 4.1.1 on 2022-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_remove_pizza_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_thin_large_pic',
            field=models.ImageField(null=True, upload_to='pizza/', verbose_name='Фото большой круг тонкое тесто'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_thin_medium_pic',
            field=models.ImageField(null=True, upload_to='pizza/', verbose_name='Фото средний круг тонкое тесто'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_trad_large_pic',
            field=models.ImageField(null=True, upload_to='pizza/', verbose_name='Фото большой круг традиционное тесто'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_trad_medium_pic',
            field=models.ImageField(null=True, upload_to='pizza/', verbose_name='Фото средний круг традиционное тесто'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_trad_small_pic',
            field=models.ImageField(null=True, upload_to='pizza/', verbose_name='Фото маленький круг традиционное тесто'),
        ),
    ]
